### PR TITLE
Add a few more Dockerfiles

### PR DESCRIPTION
**Pull request by MrSuttonmann**
I’ve added the following Dockerfiles:

- [AlmaLinux](https://hub.docker.com/_/almalinux):8
- [Amazon Linux](https://hub.docker.com/_/amazonlinux):2023
- [ArchLinux](https://hub.docker.com/_/archlinux):base
- [OracleLinux](https://hub.docker.com/_/oraclelinux):9

I’ve also ordered the list alphabetically and added a version where possible. Arch is an outlier here as they don’t provide specific version tags.

### CODE REVIEW

**Comment by steveiliop56** [comment]
Thank you! I won't merge yet tho because some of the images don't support arm64 so I want to add a small function to display only supported distros.

**Comment by steveiliop56** [comment]
Cool cool. I am planning to write tests too when I learn how 😅

**Comment by steveiliop56** [comment]
@MrSuttonmann can you update your pr so it follows the new distro "schema"

**Comment by MrSuttonmann** [comment]
@steveiliop56 Yes, however I think your branch will need to be merged into `main` first.

**Comment by MrSuttonmann** [comment]
@steveiliop56 - Done and ready to go!

**Pull request merged**
