### PR TITLE
Refactoring port checking logic

### PR DESCRIPTION
**Pull request by MrSuttonmann**
I’m all about encapsulating logic into smaller functions. The one that was bugging me here was the port checking logic.

I’ve moved it from the `createAction` where it really didn’t belong into a helper function in the `port-checker` utility file.

In addition, there’s some nicer logging.

Added bonus, I fixed a typo.

### CODE REVIEW

**Comment by steveiliop56** [comment]
Hello @MrSuttonmann,

Thank you very much! Will test and merge today!

**Comment by MrSuttonmann** [comment]
No problem! I have a bit more refactoring I'd like to do today so expect another PR soon!

**Comment by steveiliop56** [comment]
@MrSuttonmann you accidentally closed the pull request

**Comment by MrSuttonmann** [comment]
Whoops!

**Comment by steveiliop56** [comment]
Closing because of #13

**Pull request closed without merging**
